# Generated by Django 3.1.6 on 2021-02-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
