# Generated by Django 3.1.6 on 2021-02-15 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210215_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usertweet',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1980, 1, 1, 0, 1, 1)),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
