# Generated by Django 3.1.6 on 2021-02-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210215_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
