# Generated by Django 3.1.7 on 2021-02-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210215_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='description',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='usertweet',
            name='message',
            field=models.CharField(max_length=280),
        ),
    ]
