# Generated by Django 3.1.7 on 2021-02-27 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210227_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertweet',
            old_name='tweet_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usertweet',
            old_name='message',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='usertweet',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='usertweet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1980, 1, 1, 0, 1, 1)),
        ),
    ]
