# Generated by Django 3.1.7 on 2021-02-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210227_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweet',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
