# Generated by Django 3.1.6 on 2021-02-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210227_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweet',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
