# Generated by Django 3.1.7 on 2021-02-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210227_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='friends_count',
            field=models.CharField(default='0', max_length=13),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='profile_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='total_tweets',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
