# Generated by Django 3.1.7 on 2021-02-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210228_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='total_tweets',
            new_name='public_metrics',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='friends_count',
        ),
    ]
