# Generated by Django 3.1.7 on 2021-02-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210228_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='public_metrics',
            field=models.JSONField(default=dict),
        ),
    ]
