# Generated by Django 3.1.7 on 2021-02-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210228_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='public_metrics',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers_count',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='following_count',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='tweet_count',
            field=models.CharField(default='', max_length=200),
        ),
    ]
