# Generated by Django 3.1.7 on 2021-02-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_twitteruser_listed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertweet',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='sentiment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usertweet',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
