# Generated by Django 3.1.7 on 2021-03-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210228_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='bar_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
