# Generated by Django 3.1.7 on 2021-03-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_twitteruser_bar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='bar_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
